branches:
  only:
    - master
language: go
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      install:
        - pip install awscli --user
        - mkdir ${HOME}/.aws
        - echo $AWSCRED | base64 --decode -i > ${HOME}/.aws/credentials
        - aws s3 ls s3://autonity.io
      on:
        branch: master