branches:
  only:
    - master
language: go
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      install:
        - mkdir ${HOME}/.aws
        - echo $aws_cli_credentials | base64 --decode -i > ${HOME}/.aws/credentials
        - pip install awscli --user
        # - aws s3 ls s3://autonity.io
        - cat ${HOME}/.aws/credentials
      on:
        branch: master